// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetChat.Persistence;

namespace NetChat.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210715235944_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");

            modelBuilder.Entity("NetChat.Domain.Channel", b =>
                {
                    b.Property<Guid>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            ChannelId = new Guid("9995b226-584f-4c2d-9dc3-3b81f6d0105c"),
                            Description = "DotNetCore full stack",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            ChannelId = new Guid("fc6f119a-28a2-4fb2-a3fc-8731264b8c43"),
                            Description = "Python Developer",
                            Name = "Python"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
